[Variables]
;Phone Variables
phoneSize = 1
backgroundImage = #@#Images\Phone\Background#phoneSize#.png

;Room Variables
roomSize = 3
roomWall = #@#Images\Room\Walls\Gray#roomSize#.png

;Item Variables
kiraMikiPoster =1
alexFigurine =1
assortedCartridges =1
beerOnDiscount =1
can =0
clock =1
clothesRack =1
crackedDaruma =0
cuteClayHouses =1
cutesyGamePoster =1
holoPlant =1
jokerCyclone =1
kiraMikiBanner =1
manekiNeko =1
megaChristmasTree =1
moviePoster =1
paperLantern =1
pC9X =1
replicaToyTuring =1




