[Variables]
;Phone Variables
phoneSize = 1
backgroundImage = #@#Images\Phone\Lock Screen\Background#phoneSize#.png

;Room Variables
roomSize =3
roomWall = #@#Images\Room\Walls\Gray#roomSize#.png

;Item Variables
;TODO change from here to Items Text.inc
kiraMikiPoster =0

alexFigurine =0
assortedCartridges =0
beerOnDiscount =0
can =0
clock =0
clothesRack =0
crackedDaruma =1
cuteClayHouses =0
cutesyGamePoster =0
holoPlant =0
jokerCyclone =1
kiraMikiBanner =1
manekiNeko =0
megaChristmasTree =0
moviePoster =0
paperLantern =0
pC9X =0
replicaToyTuring =0




